// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApi.Data;

#nullable disable

namespace StockApi.Migrations
{
    [DbContext(typeof(LondonStockContext))]
    partial class LondonStockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockApi.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Share")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Share = 33,
                            StockName = "Apple Inc.",
                            Ticker = "AAPL",
                            Value = "£197.11"
                        },
                        new
                        {
                            Id = 2,
                            Share = 82,
                            StockName = "Apple Inc.",
                            Ticker = "TSLA",
                            Value = "£307.70"
                        },
                        new
                        {
                            Id = 3,
                            Share = 12,
                            StockName = "Microsoft Corp.",
                            Ticker = "MSFT",
                            Value = "£309.37"
                        },
                        new
                        {
                            Id = 4,
                            Share = 41,
                            StockName = "Nvidia Corp.",
                            Ticker = "NVDA",
                            Value = "£135.51"
                        },
                        new
                        {
                            Id = 5,
                            Share = 166,
                            StockName = "Rush Street Interactive.",
                            Ticker = "RSI",
                            Value = "£12.90"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
